# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae433edfa0215dacecb876a71a0b2dd8747ae5d7af62b8afc090dbab217aac75af85cdebb8d84290d685030f106da91589ca20ecd6571ea9a30977b39f50d203

test:
  secret_key_base: 234dc156e62a4f02d2e9e1b327fa9b811e69ac3841e05d88286e23acce0f7bc35067f657b77bf98ac03a4f362fb0d38e058abcdc1b88f266c733c14c0e50006f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
